version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/site"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
