version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/zavod"
    open-pull-requests-limit: 99
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
