version: "2"

services:
  app:
    build: .
    image: pudo/opensanctions:latest
    command: opensanctions run
    hostname: work
    volumes:
      - "./data:/opensanctions/data"
      - "./opensanctions:/opensanctions/opensanctions"
    tmpfs:
      - "/tmp"
