site_name: zavod
repo_url: https://github.com/opensanctions/opensanctions

theme:
  name: material
  logo: https://assets.opensanctions.org/images/ura/logo_white.png
  favicon: https://assets.opensanctions.org/images/favicon-32x32.png
  palette:
    primary: custom
    accent: custom
  extra_css: [stylesheets/extra.css]

extra:
  social:
    - icon: material/web
      link: https://www.opensanctions.org/
    - icon: material/mail
      link: https://www.opensanctions.org/contact/
    - icon: material/slack
      link: https://www.opensanctions.org/slack/
    - icon: material/github
      link: https://github.com/opensanctions/opensanctions

plugins:
  - autorefs
  # - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - install.md
  - Tutorial: tutorial.md
  - Command-line usage: usage.md
  - context.md
  - helpers.md
  - patterns.md
