type: collection
title: OpenSanctions Default
deploy:
  schedule: "30 */5 * * *"
  memory: "1500Mi"
  memory_limit: "2500Mi"
  cpu: "500m"
  disk: "20Gi"
  command: /etl/scripts/export-default.sh
  # premium: true
exports:
  - statistics.json
  - entities.ftm.json
  - names.txt
  - senzing.json
  - targets.nested.json
  - targets.simple.csv
  - statements.csv
summary: >
  This distribution includes the data collected by OpenSanctions that
  meets quality standards and would be useful in a screening system or
  for investigative use.
description: |
  This list can be used as the broadest available OpenSanctions dataset. It
  includes any entity that should receive enhanced public scrutiny - either
  because they appear on a sanctions list, in a criminal context or as a
  political office holder.

  Be advised that the data in this collection originates from a variety of
  sources and therefore varies in terms of detail and precision. For example,
  many listings of political office holders do not include their exact birth
  dates or full given names.
children:
  - sanctions
  - crime
  - peps
  - debarment
  - wanted
  - enrichers

  # misc
  - ann_graph_topics
  - wd_oligarchs
  - wd_curated
  - ru_navalny35
  - ru_billionaires_2021
  - ru_acf_bribetakers
  - ru_nsd_isin
  - sy_obsalytics_opensyr
  - md_rise_profiles
  - ru_myrotvorets_wagner
  - ransomwhere
  - kp_rusi_reports
