name: ETL Process for UAE Local Terrorist List

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Allows manual triggers

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          pip install pyicu plyvel xlrd normality zavod rigour nomenklatura
          pip install -e './zavod[dev]'

      - name: Fix nomenklatura compatibility issues
        run: |
          # Fix import issues by adding 'Self' from typing
          sed -i '1i from typing import Self' $(python -c "import nomenklatura; print(nomenklatura.__path__[0])")/dataset/dataset.py
          # Replace 'Self' with 'Any' if necessary
          sed -i 's/self: Self/self: Any/g' $(python -c "import nomenklatura; print(nomenklatura.__path__[0])")/dataset/dataset.py
          sed -i 's/Self/Any/g' $(python -c "import nomenklatura; print(nomenklatura.__path__[0])")/dataset/dataset.py

      - name: Run ETL Process (Crawl)
        run: |
          zavod crawl ./datasets/ae/local_terrorists/ae_local_terrorists.yml

      - name: Set ZAVOD_RESOLVER_PATH
        run: |
          echo "ZAVOD_RESOLVER_PATH=${GITHUB_WORKSPACE}/zavod/zavod/resolver" >> $GITHUB_ENV
      - name: Create directories
        run: |
          mkdir -p ./data    

      - name: Run ETL Export
        run: |
          zavod export ./datasets/ae/local_terrorists/ae_local_terrorists.yml

      - name: Find targets.nested.json file
        run: |
          find . -name "targets.nested.json"
      - name: List all untracked files
        run: |
          git status

      - name: Commit ETL output to repository
        run: |
          git config --global user.name "AnalyzeJayWhiz"
          git config --global user.email "jaymehta130@gmail.com"
          git add ./data/datasets/ae_local_terrorists/*  # Ensure the correct path is added here
          git commit -m "Add ETL output"
          git push origin main
