name: build

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Set env
        run: echo "VERSION_NUMBER=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}
      - name: Build and push release
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pudo/opensanctions:latest
