name: Daily Crawl Execution

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: "0 12 * * *"

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Find and run all crawl.py scripts
      - name: Run All Crawl Scripts
        run: |
          for script in $(find . -name "crawl.py"); do
            echo "Running $script..."
            python "$script" || echo "Error running $script"
          done
