name: integration

on:
  push: {}
  workflow_dispatch: {}

jobs:
  docker:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}
      - name: Build and push release
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pudo/opensanctions:latest
          cache-from: type=registry,ref=pudo/opensanctions:latest
          cache-to: type=inline
  index:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [docker]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_REGION: eu-central-1
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # - name: Set env
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
      #     echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
      - name: Fetch database state from data.opensanctions.org
        run: |
          mkdir -p data/state
          aws s3 sync --no-progress s3://data.opensanctions.org/state data/state
      - name: Index default dataset
        run: |
          docker run \
            -v `pwd`/data:/opensanctions/data \
            pudo/opensanctions \
            opensanctions index default
      - name: Upload index to data.opensanctions.org
        if: ${{ always() }}
        run: |
          aws s3 sync --no-progress --acl public-read data/index s3://data.opensanctions.org/index
  api:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_user }}
          password: ${{ secrets.docker_password }}
      - name: Build and push release
        uses: docker/build-push-action@v2
        with:
          context: api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: pudo/opensanctions-api:latest
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev
          pip install --no-cache-dir -q pyicu awscli
          pip install --no-cache-dir -q -e ".[dev]"
          pip freeze
      - name: Run a single dataset
        run: |
          opensanctions run us_ofac_cons
      - name: Build a distribution
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish opensanctions to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: dist/
          skip_existing: true
  site:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_REGION: eu-central-1
    defaults:
      run:
        working-directory: ./site
    steps:
      - uses: actions/checkout@v2
      - name: Install awscli
        run: pip install -q -U awscli
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm install
      - name: Download opensanctions data
        run: make data
      - name: Build and export site
        run: npm run build
      - name: Publish draft to beta.opensanctions.org
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          aws s3 sync --delete --no-progress --acl public-read out s3://beta.opensanctions.org
      - name: Publish site to opensanctions.org
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws s3 sync --no-progress --cache-control "public, max-age=846000" --acl public-read out/_next s3://opensanctions.org/_next
          aws s3 sync --no-progress --cache-control "public, max-age=423000" --acl public-read out/static s3://opensanctions.org/static
          aws s3 sync --delete --no-progress --cache-control "public, max-age=3600" --acl public-read out s3://opensanctions.org
          aws cloudfront create-invalidation --distribution-id E321O1ATKKHDQT --paths "/*"
