name: lint_crawlers

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get modified dataset yamls
        id: changed-yamls
        uses: tj-actions/changed-files@v43
        with:
          files: 'datasets/**/*.y*ml'
      - name: Lint modiied dataset yamls
        #if: ${{ steps.changed-yamls.outputs.all_changed_files != '' }}
        run: |
          for dataset in ${{ steps.changed-yamls.outputs.all_changed_files }}
          do
              echo Linting $dataset
              yamllint $dataset
          done
