name: long

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}

jobs:
  crawl:
    runs-on: ubuntu-latest
    container: ghcr.io/opensanctions/opensanctions
    env:
      OPENSANCTIONS_COH_API_KEY: ${{ secrets.OPENSANCTIONS_COH_API_KEY }}
      OPENSANCTIONS_DATABASE_URI: ${{ secrets.OPENSANCTIONS_DATABASE_URI }}
    strategy:
      fail-fast: false
      matrix:
        crawler:
          - interpol_red_notices
          - interpol_yellow_notices
          - wd_peppercat_leaders
          - wd_peppercat_legislators
          # - ru_rupep
    steps:
      - name: Crawl data sources
        env:
          CRAWLER: ${{ matrix.crawler }}
        run: |
          opensanctions crawl $CRAWLER
