name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch. Change this if needed.
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub UI

jobs:
  configure-pages:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev libsnappy-dev build-essential

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyicu plyvel xlrd normality zavod rigour nomenklatura

      # Run your Python ETL script (this is where your script is executed)
      - name: Run Python ETL script
        run: |
          python your_script.py  # Replace with the actual Python script you're using

      # Set up GitHub Pages (GitHub Pages Configuration)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true  # Ensures Pages is enabled in repository settings
          branch: gh-pages  # Specifies the branch for GitHub Pages (e.g., 'gh-pages')

      # Build your site (if you need to build the site before pushing to Pages)
      # For example, if you're using a static site generator like Jekyll, replace with your actual build commands
      - name: Build the Site
        run: |
          # Example of building the site. Replace with actual commands to build your site
          echo "Building the site..."
          # Example: jekyll build --destination _site

      # Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          # Push the built site to the gh-pages branch
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          git add -A
          git commit -m "Deploy site to GitHub Pages"
          git push -f origin gh-pages  # Push to the gh-pages branch

      # Clean up: Optionally, clean up any unnecessary files or branches
      - name: Clean up
        run: |
          echo "Cleaning up..."
          # Any cleanup commands you may need
