name: OpenSanctions Workflow

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Set the appropriate Python version

    # Install system dependencies (needed by zavod and other libraries)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libicu-dev libsnappy-dev build-essential
        python -m pip install --upgrade pip
        python -m pip install pyicu plyvel xlrd normality zavod rigour nomenklatura

    # Run the OpenSanctions Python script
    - name: Run OpenSanctions Script
      run: |
        # Install the OpenSanctions repo and other dependencies
        pip install -e ./zavod[dev]
        pip install -r ./opensanctions/contrib/delta/requirements.txt
        
        # Set the export path relative to the repository structure
        export_path="/home/runner/work/opensanctions"  # This is where the data will be stored

        # Run your Python script with the correct export path
        python ./opensanctions/your_script.py  # Ensure your script is located here
