name: production

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install awscli
        run: |
          pip install --upgrade -q awscli
      - name: Set env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          OPENSANCTIONS_COH_API_KEY: ${{ secrets.OPENSANCTIONS_COH_API_KEY }}
        run: |
          echo "OPENSANCTIONS_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "OPENSANCTIONS_COH_API_KEY=$OPENSANCTIONS_COH_API_KEY" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
      - name: Fetch database state from data.opensanctions.org
        run: |
          mkdir -p data/state
          aws s3 sync --no-progress s3://data.opensanctions.org/state data/state
      - name: Crawl data sources
        run: |
          docker run \
            -v `pwd`/data:/opensanctions/data \
            -e OPENSANCTIONS_COH_API_KEY \
            -e OPENSANCTIONS_DATE \
            pudo/opensanctions \
            opensanctions crawl
      - name: Export data dumps
        run: |
          docker run \
            -v `pwd`/data:/opensanctions/data \
            -e OPENSANCTIONS_DATE \
            pudo/opensanctions \
            opensanctions export
      - name: Compress database
        run: |
          sqlite3 -version
          sqlite3 data/state/opensanctions.sqlite "VACUUM;"
      - name: Upload fetched resources to data.opensanctions.org
        if: ${{ always() }}
        run: |
          aws s3 sync --no-progress --cache-control "public, max-age=846000" --acl public-read data/datasets s3://data.opensanctions.org/datasets/$OPENSANCTIONS_DATE
      - name: Publish data to data.opensanctions.org
        run: |
          aws s3 sync --delete --no-progress --acl public-read data/state s3://data.opensanctions.org/state
          aws s3 sync --delete --no-progress --cache-control "public, max-age=42300" --metadata-directive REPLACE --acl public-read data/datasets s3://data.opensanctions.org/datasets/latest
          aws s3 sync --delete --no-progress --cache-control "public, max-age=84600" --metadata-directive REPLACE --acl public-read data/datasets s3://data.opensanctions.org/datasets/$OPENSANCTIONS_DATE
          aws cloudfront create-invalidation --distribution-id ETROMAQBEJS91 --paths "/datasets/latest/*"
  site:
    needs: [data]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_REGION: eu-central-1
    defaults:
      run:
        working-directory: ./site
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Install awscli
        run: pip install -q -U awscli
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm install
      - name: Download opensanctions data
        run: make data
      - name: Build and export site
        run: npm run build
      - name: Publish site to opensanctions.org
        run: |
          aws s3 sync --no-progress --cache-control "public, max-age=846000" --acl public-read out/_next s3://opensanctions.org/_next
          aws s3 sync --no-progress --cache-control "public, max-age=423000" --acl public-read out/static s3://opensanctions.org/static
          aws s3 sync --delete --no-progress --cache-control "public, max-age=3600" --acl public-read out s3://opensanctions.org
          aws cloudfront create-invalidation --distribution-id E321O1ATKKHDQT --paths "/*"
