name: test

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show ref
        run: |
          echo "$GITHUB_REF"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq libicu-dev
          pip install wheel pyicu
          pip install -e .
      - name: Run a single dataset
        run: |
          opensanctions run us_ofac_cons
    