name: test

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install -y -qq libicu-dev
          pip install --no-cache-dir -q pyicu awscli
          pip install --no-cache-dir -q -e .
      - name: Run a single dataset
        if: ${{ github.ref != 'refs/heads/production' }}
        run: |
          opensanctions run us_ofac_cons
